In [1]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'Listings.csv', 'Reviews_data_dictionary.csv', 'Reviews.csv', 'Listings_data_dictionary.csv', 'sample_data']

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.2

In [4]:
import pandas as pd

In [5]:
listings = pd.read_csv('Listings.csv', encoding='latin1')

/tmp/ipykernel_2806/1148699358.py:1: DtypeWarning: Columns (5,13) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv('Listings.csv', encoding='latin1')

In [6]:
reviews = pd.read_csv('Reviews.csv', encoding='latin1')

In [7]:
print("Listings Shape:", listings.shape)

Listings Shape: (279712, 33)

In [8]:
print("Reviews Shape:", reviews.shape)

Reviews Shape: (5373143, 4)

In [9]:
listings.head()

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [10]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279537 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  object
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: float64(13), int64(6), object(14)
memory usage: 70.4+ MB

In [11]:
listings.describe()

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
count,2.797120e+05,2.797120e+05,150930.000000,166625.000000,279547.000000,279712.000000,279712.000000,279712.000000,250277.000000,279712.000000,279712.000000,2.797120e+05,188307.000000,187999.000000,188047.000000,187941.000000,188025.000000,187937.000000,187927.000000
mean,2.638196e+07,1.081658e+08,0.865939,0.827168,24.581612,18.761862,12.595075,3.288736,1.515509,608.792737,8.050967,2.755860e+04,93.405195,9.565476,9.312869,9.701534,9.698593,9.633994,9.335364
std,1.442576e+07,1.108570e+08,0.283744,0.289202,284.041143,32.560343,73.081309,2.133379,1.153080,3441.826611,31.518946,7.282875e+06,10.070437,0.990878,1.146072,0.867434,0.886884,0.833234,1.042625
min,2.577000e+03,1.822000e+03,0.000000,0.000000,0.000000,-34.264400,-99.339630,0.000000,1.000000,0.000000,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.384462e+07,1.720656e+07,0.900000,0.780000,1.000000,-22.964390,-43.198040,2.000000,1.000000,75.000000,1.000000,4.500000e+01,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000
50%,2.767098e+07,5.826911e+07,1.000000,0.980000,1.000000,40.710785,2.382780,2.000000,1.000000,150.000000,2.000000,1.125000e+03,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
75%,3.978485e+07,1.832853e+08,1.000000,1.000000,4.000000,41.908610,28.986730,4.000000,2.000000,474.000000,5.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
max,4.834353e+07,3.901874e+08,1.000000,1.000000,7235.000000,48.904910,151.339810,16.000000,50.000000,625216.000000,9999.000000,2.147484e+09,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [12]:
listings.isnull().sum()

listing_id                          0
name                              175
host_id                             0
host_since                        165
host_location                     840
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                 165
host_total_listings_count         165
host_has_profile_pic              165
host_identity_verified            165
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                        29435
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating            91405
review_scores_accuracy          91713
review_scores_cleanliness       91665
review_scores_checkin           91771
review_scores_communication     91687
review_scores_location          91775
review_scores_value             91785
instant_bookable                    0
dtype: int64

In [13]:
df = listings.copy()

In [14]:
missing = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing %': round((df.isnull().sum()/len(df))*100,2)
})

missing.sort_values('Missing %', ascending=False)

                             Missing Count  Missing %
district                            242700      86.77
host_response_time                  128782      46.04
host_response_rate                  128782      46.04
host_acceptance_rate                113087      40.43
review_scores_value                  91785      32.81
review_scores_location               91775      32.81
review_scores_checkin                91771      32.81
review_scores_accuracy               91713      32.79
review_scores_communication          91687      32.78
review_scores_cleanliness            91665      32.77
review_scores_rating                 91405      32.68
bedrooms                             29435      10.52
host_location                          840       0.30
host_total_listings_count              165       0.06
name                                   175       0.06
host_is_superhost                      165       0.06
host_since                             165       0.06
host_identity_verified                 165       0.06
host_has_profile_pic                   165       0.06
listing_id                               0       0.00
longitude                                0       0.00
host_id                                  0       0.00
latitude                                 0       0.00
city                                     0       0.00
neighbourhood                            0       0.00
maximum_nights                           0       0.00
minimum_nights                           0       0.00
price                                    0       0.00
amenities                                0       0.00
accommodates                             0       0.00
room_type                                0       0.00
property_type                            0       0.00
instant_bookable                         0       0.00

In [15]:
df.drop('district', axis=1, inplace=True)

In [16]:
host_cols = [
    'host_since',
    'host_location',
    'host_response_time',
    'host_is_superhost',
    'host_has_profile_pic',
    'host_identity_verified'
]

for col in host_cols:
    df[col] = df[col].fillna('Unknown')

In [17]:
num_cols = [
    'host_response_rate',
    'host_acceptance_rate',
    'host_total_listings_count'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [18]:
df['bedrooms'].fillna(df['bedrooms'].median(), inplace=True)

/tmp/ipykernel_2806/2616886916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bedrooms'].fillna(df['bedrooms'].median(), inplace=True)

In [19]:
review_cols = [
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value'
]

for col in review_cols:
    df[col] = df[col].fillna(df[col].median())

In [20]:
df['name'].fillna('Unknown Listing', inplace=True)

/tmp/ipykernel_2806/1133955430.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['name'].fillna('Unknown Listing', inplace=True)

In [21]:
df['host_since'] = pd.to_datetime(
    df['host_since'],
    errors='coerce'
)

In [22]:
df.isnull().sum()

listing_id                       0
name                             0
host_id                          0
host_since                     165
host_location                    0
host_response_time               0
host_response_rate               0
host_acceptance_rate             0
host_is_superhost                0
host_total_listings_count        0
host_has_profile_pic             0
host_identity_verified           0
neighbourhood                    0
city                             0
latitude                         0
longitude                        0
property_type                    0
room_type                        0
accommodates                     0
bedrooms                         0
amenities                        0
price                            0
minimum_nights                   0
maximum_nights                   0
review_scores_rating             0
review_scores_accuracy           0
review_scores_cleanliness        0
review_scores_checkin            0
review_scores_communication      0
review_scores_location           0
review_scores_value              0
instant_bookable                 0
dtype: int64

In [23]:
df['host_since'] = df['host_since'].fillna(df['host_since'].min())

In [24]:
df.isnull().sum()

listing_id                     0
name                           0
host_id                        0
host_since                     0
host_location                  0
host_response_time             0
host_response_rate             0
host_acceptance_rate           0
host_is_superhost              0
host_total_listings_count      0
host_has_profile_pic           0
host_identity_verified         0
neighbourhood                  0
city                           0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bedrooms                       0
amenities                      0
price                          0
minimum_nights                 0
maximum_nights                 0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
instant_bookable               0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df['price'].describe()

count    279712.000000
mean        608.792737
std        3441.826611
min           0.000000
25%          75.000000
50%         150.000000
75%         474.000000
max      625216.000000
Name: price, dtype: float64

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
print("Original Dataset Shape:", df.shape)
print("Cleaned Dataset Shape :", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum())

Original Dataset Shape: (279712, 32)

NameError: name 'df_clean' is not defined

In [29]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

df_clean = df[
    (df['price'] >= 0) &
    (df['price'] <= upper_bound)
].copy()

Lower Bound: -523.5
Upper Bound: 1072.5

In [30]:
print("Original Dataset Shape:", df.shape)
print("Cleaned Dataset Shape :", df_clean.shape)

Original Dataset Shape: (279712, 32)
Cleaned Dataset Shape : (248317, 32)

In [31]:
df_clean.isnull().sum()

listing_id                     0
name                           0
host_id                        0
host_since                     0
host_location                  0
host_response_time             0
host_response_rate             0
host_acceptance_rate           0
host_is_superhost              0
host_total_listings_count      0
host_has_profile_pic           0
host_identity_verified         0
neighbourhood                  0
city                           0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bedrooms                       0
amenities                      0
price                          0
minimum_nights                 0
maximum_nights                 0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
instant_bookable               0
dtype: int64

In [32]:
df_clean.to_csv('Listings_Cleaned.csv', index=False)

In [33]:
from google.colab import files
files.download('Listings_Cleaned.csv')

In [34]:
reviews.shape

(5373143, 4)

In [35]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5373143 entries, 0 to 5373142
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   listing_id   int64
 1   review_id    int64
 2   date         object
 3   reviewer_id  int64
dtypes: int64(3), object(1)
memory usage: 164.0+ MB

In [36]:
reviews.isnull().sum()

listing_id     0
review_id      0
date           0
reviewer_id    0
dtype: int64

In [37]:
reviews.duplicated().sum()

np.int64(0)

In [38]:
reviews.columns

Index(['listing_id', 'review_id', 'date', 'reviewer_id'], dtype='object')

In [39]:
reviews['date'] = pd.to_datetime(
    reviews['date'],
    errors='coerce'
)

In [40]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5373143 entries, 0 to 5373142
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   listing_id   int64
 1   review_id    int64
 2   date         datetime64[ns]
 3   reviewer_id  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 164.0 MB

In [41]:
reviews['review_year'] = reviews['date'].dt.year
reviews['review_month'] = reviews['date'].dt.month_name()

In [42]:
df_clean.shape

(248317, 32)

In [43]:
reviews.to_csv(
    'Reviews_Cleaned.csv',
    index=False
)

In [44]:
from google.colab import files

files.download('Reviews_Cleaned.csv')